import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('Start seeding...');

    // Clear existing data
    await prisma.carImage.deleteMany({});
    await prisma.car.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.testimonial.deleteMany({});

    // Create a default user
    const user = await prisma.user.create({
        data: {
            email: 'admin@example.com',
            firstName: 'Admin',
            lastName: 'User',
            role: 'admin',
        },
    });

    const carsData = [
        {
            make: 'Toyota', model: 'Camry', year: 2021, price: 25000, mileage: 30000, horsepower: 203, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Mid-size Sedan', engineVolume: 2.5, cylinders: 4, driveWheels: 'FWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Super White', interiorColor: 'Black', interiorMaterial: 'Fabric',
            exchange: true, technicalInspection: true, engineCode: 'A25A-FKS', paintCode: '040', topSpeed: 135, zeroToSixty: 7.6, length: 192.1, width: 72.4, height: 56.9, wheelbase: 111.2, cargoCapacity: 15.1, groundClearance: 5.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Power Windows', 'Central Locking', 'Climate Control', 'Heated Seats'],
            safety: ['ABS', 'ESP', 'Airbags', 'Traction Control'],
            multimedia: ['Bluetooth', 'USB', 'Apple CarPlay', 'Android Auto'],
            other: ['Alloy Wheels', 'Fog Lights'],
            features: ['Backup Camera', 'Bluetooth', 'Apple CarPlay'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Toyota+Camry+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Toyota+Camry+2'],
        },
        {
            make: 'Honda', model: 'Civic', year: 2022, price: 22000, mileage: 15000, horsepower: 158, fuelType: 'Gasoline', transmission: 'CVT', bodyStyle: 'Sedan',
            category: 'Compact Sedan', engineVolume: 2.0, cylinders: 4, driveWheels: 'FWD', doors: 4, airbags: 6, wheel: 'Left', color: 'Aegean Blue Metallic', interiorColor: 'Gray', interiorMaterial: 'Cloth',
            exchange: false, technicalInspection: true, engineCode: 'K20C2', paintCode: 'B-593M', topSpeed: 130, zeroToSixty: 8.5, length: 184.0, width: 70.9, height: 55.7, wheelbase: 107.7, cargoCapacity: 14.8, groundClearance: 6.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Keyless Entry', 'Cruise Control', 'Automatic Climate Control'],
            safety: ['Lane Keeping Assist', 'Adaptive Cruise Control', 'Forward Collision Warning'],
            multimedia: ['7-inch Touchscreen', 'Bluetooth', 'Android Auto'],
            other: ['LED Headlights', '16-inch Alloy Wheels'],
            features: ['Lane Keeping Assist', 'Adaptive Cruise Control', 'Android Auto'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Honda+Civic+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Honda+Civic+2'],
        },
        {
            make: 'Ford', model: 'F-150', year: 2020, price: 35000, mileage: 40000, horsepower: 325, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Truck',
            category: 'Full-size Truck', engineVolume: 2.7, cylinders: 6, driveWheels: '4WD', doors: 4, airbags: 6, wheel: 'Left', color: 'Oxford White', interiorColor: 'Medium Earth Gray', interiorMaterial: 'Vinyl',
            exchange: true, technicalInspection: false, engineCode: 'EcoBoost', paintCode: 'YZ', topSpeed: 107, zeroToSixty: 6.3, length: 231.9, width: 79.9, height: 77.2, wheelbase: 145.0, cargoCapacity: 52.8, groundClearance: 9.4,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Air Conditioning', 'Power Steering'],
            safety: ['Rearview Camera', 'Tire Pressure Monitoring'],
            multimedia: ['SYNC 3', 'FordPass Connect'],
            other: ['Towing Package'],
            features: ['Towing Package', 'Pro Trailer Backup Assist', 'SYNC 3'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Ford+F-150+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Ford+F-150+2'],
        },
        {
            make: 'Tesla', model: 'Model 3', year: 2022, price: 45000, mileage: 10000, horsepower: 283, fuelType: 'Electric', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Electric Sedan', engineVolume: null, cylinders: null, driveWheels: 'RWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Pearl White Multi-Coat', interiorColor: 'All Black', interiorMaterial: 'Synthetic Leather',
            exchange: false, technicalInspection: true, engineCode: 'AC Induction', paintCode: 'PPSW', topSpeed: 140, zeroToSixty: 5.3, length: 184.8, width: 72.8, height: 56.8, wheelbase: 113.2, cargoCapacity: 15.0, groundClearance: 5.5,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Heated Front and Rear Seats', 'Dual-Zone Climate Control', 'Tinted Glass Roof'],
            safety: ['Autopilot', 'Automatic Emergency Braking', 'Blind Spot Monitoring'],
            multimedia: ['15-inch Touchscreen', 'Premium Audio System', 'Navigation'],
            other: ['18-inch Aero Wheels', 'LED Fog Lamps'],
            features: ['Autopilot', 'Full Self-Driving Capability', 'Premium Interior'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Tesla+Model+3+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Tesla+Model+3+2'],
        },
        {
            make: 'BMW', model: '3 Series', year: 2021, price: 42000, mileage: 20000, horsepower: 255, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Luxury Compact Sedan', engineVolume: 2.0, cylinders: 4, driveWheels: 'RWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Alpine White', interiorColor: 'Black SensaTec', interiorMaterial: 'Synthetic Leather',
            exchange: true, technicalInspection: true, engineCode: 'B48', paintCode: '300', topSpeed: 155, zeroToSixty: 5.6, length: 185.7, width: 71.9, height: 56.8, wheelbase: 112.2, cargoCapacity: 17.0, groundClearance: 5.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Sunroof', 'Multi-zone Climate Control', 'Power Front Seats'],
            safety: ['Active Driving Assistant', 'Frontal Collision Warning', 'Lane Departure Warning'],
            multimedia: ['iDrive 7.0', 'Apple CarPlay', '10-speaker HiFi Sound System'],
            other: ['18-inch V-spoke Wheels', 'LED Headlights'],
            features: ['Live Cockpit Pro', 'iDrive 7.0', 'Active Driving Assistant'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=BMW+3+Series+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=BMW+3+Series+2'],
        },
        {
            make: 'Mercedes-Benz', model: 'C-Class', year: 2022, price: 48000, mileage: 12000, horsepower: 255, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Luxury Compact Sedan', engineVolume: 2.0, cylinders: 4, driveWheels: 'RWD', doors: 4, airbags: 9, wheel: 'Left', color: 'Polar White', interiorColor: 'Black MB-Tex', interiorMaterial: 'Synthetic Leather',
            exchange: false, technicalInspection: true, engineCode: 'M254', paintCode: '149', topSpeed: 130, zeroToSixty: 5.9, length: 187.0, width: 71.7, height: 56.3, wheelbase: 112.8, cargoCapacity: 12.6, groundClearance: 3.8,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Power Front Seats with Memory', 'Dual-Zone Automatic Climate Control', 'Sunroof'],
            safety: ['PRE-SAFE', 'Active Brake Assist', 'Blind Spot Assist'],
            multimedia: ['MBUX Infotainment System', '11.9-inch Touchscreen', 'Biometric Authentication'],
            other: ['18-inch Multispoke Wheels', 'LED High Performance Headlamps'],
            features: ['MBUX Infotainment System', 'Digital Instrument Cluster', 'PRE-SAFE'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Mercedes-Benz+C-Class+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Mercedes-Benz+C-Class+2'],
        },
        {
            make: 'Audi', model: 'A4', year: 2021, price: 40000, mileage: 18000, horsepower: 201, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Luxury Compact Sedan', engineVolume: 2.0, cylinders: 4, driveWheels: 'AWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Ibis White', interiorColor: 'Black', interiorMaterial: 'Leather',
            exchange: true, technicalInspection: true, engineCode: 'EA888', paintCode: 'T9T9', topSpeed: 130, zeroToSixty: 6.3, length: 187.5, width: 72.7, height: 56.2, wheelbase: 111.0, cargoCapacity: 12.0, groundClearance: 5.2,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Heated Front Seats', 'Three-zone Automatic Climate Control', 'Sunroof'],
            safety: ['Audi Pre Sense City', 'Lane Departure Warning', 'High-beam Assist'],
            multimedia: ['MMI Touch Display', 'Audi Smartphone Interface', '10-speaker Sound System'],
            other: ['17-inch 10-spoke Wheels', 'LED Headlights'],
            features: ['Virtual Cockpit', 'MMI Touch Response', 'Audi Pre Sense City'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Audi+A4+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Audi+A4+2'],
        },
        {
            make: 'Jeep', model: 'Wrangler', year: 2020, price: 32000, mileage: 35000, horsepower: 285, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Off-road SUV', engineVolume: 3.6, cylinders: 6, driveWheels: '4WD', doors: 4, airbags: 4, wheel: 'Left', color: 'Bright White', interiorColor: 'Black', interiorMaterial: 'Cloth',
            exchange: true, technicalInspection: true, engineCode: 'Pentastar', paintCode: 'PW7', topSpeed: 97, zeroToSixty: 6.8, length: 188.4, width: 73.8, height: 73.6, wheelbase: 118.4, cargoCapacity: 31.7, groundClearance: 10.8,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Air Conditioning', 'Removable Top and Doors'],
            safety: ['Hill Start Assist', 'Traction Control', 'Electronic Stability Control'],
            multimedia: ['Uconnect System', '7-inch Display', 'Bluetooth'],
            other: ['17-inch Steel Wheels', 'All-Terrain Tires'],
            features: ['Removable Top and Doors', 'Uconnect System', 'Off-Road Tires'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Jeep+Wrangler+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Jeep+Wrangler+2'],
        },
        {
            make: 'Subaru', model: 'Outback', year: 2022, price: 30000, mileage: 10000, horsepower: 182, fuelType: 'Gasoline', transmission: 'CVT', bodyStyle: 'SUV',
            category: 'Crossover SUV', engineVolume: 2.5, cylinders: 4, driveWheels: 'AWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Crystal White Pearl', interiorColor: 'Slate Black', interiorMaterial: 'Cloth',
            exchange: false, technicalInspection: true, engineCode: 'FB25', paintCode: 'K1X', topSpeed: 120, zeroToSixty: 8.7, length: 191.3, width: 73.0, height: 66.1, wheelbase: 108.1, cargoCapacity: 32.5, groundClearance: 8.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Automatic Climate Control', 'Cargo-area Release Levers'],
            safety: ['EyeSight Driver Assist Technology', 'Symmetrical All-Wheel Drive', 'High Beam Assist'],
            multimedia: ['STARLINK Multimedia', 'Dual 7.0-inch Screens', 'Apple CarPlay'],
            other: ['Raised Roof Rails', 'LED Steering Responsive Headlights'],
            features: ['Symmetrical All-Wheel Drive', 'EyeSight Driver Assist Technology', 'STARLINK Multimedia'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Subaru+Outback+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Subaru+Outback+2'],
        },
        {
            make: 'Porsche', model: '911', year: 2021, price: 110000, mileage: 8000, horsepower: 379, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Coupe',
            category: 'Sports Car', engineVolume: 3.0, cylinders: 6, driveWheels: 'RWD', doors: 2, airbags: 6, wheel: 'Left', color: 'Guards Red', interiorColor: 'Black', interiorMaterial: 'Leather',
            exchange: false, technicalInspection: true, engineCode: '9A2', paintCode: 'G1', topSpeed: 182, zeroToSixty: 4.0, length: 177.9, width: 72.9, height: 51.1, wheelbase: 96.5, cargoCapacity: 4.6, groundClearance: 4.2,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['2-zone Automatic Climate Control', 'Heated Front Seats', 'ParkAssist'],
            safety: ['Porsche Active Suspension Management (PASM)', 'Wet Mode', 'Warn and Brake Assist'],
            multimedia: ['Porsche Communication Management (PCM)', '10.9-inch Touchscreen', 'Sound Package Plus'],
            other: ['20/21-inch Carrera Wheels', 'LED Headlights'],
            features: ['Porsche Communication Management (PCM)', 'Porsche Active Suspension Management (PASM)', 'Sport Chrono Package'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Porsche+911+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Porsche+911+2'],
        },
        {
            make: 'Lexus', model: 'RX', year: 2022, price: 55000, mileage: 9000, horsepower: 295, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Luxury Crossover SUV', engineVolume: 3.5, cylinders: 6, driveWheels: 'AWD', doors: 4, airbags: 10, wheel: 'Left', color: 'Eminent White Pearl', interiorColor: 'Parchment NuLuxe', interiorMaterial: 'Synthetic Leather',
            exchange: true, technicalInspection: true, engineCode: '2GR-FKS', paintCode: '085', topSpeed: 124, zeroToSixty: 7.9, length: 192.5, width: 74.6, height: 67.7, wheelbase: 109.8, cargoCapacity: 16.0, groundClearance: 8.2,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Power Tilt-and-Telescopic Steering Column', 'Dual-zone Climate Control', 'Power Rear Door'],
            safety: ['Lexus Safety System+ 2.0', 'Blind Spot Monitor', 'Rear Cross-Traffic Alert'],
            multimedia: ['8-inch Touchscreen', 'Apple CarPlay', 'Amazon Alexa'],
            other: ['18-inch Split-five-spoke Alloy Wheels', 'Bi-LED Headlamps'],
            features: ['Lexus Safety System+ 2.0', 'Remote Touchpad', 'Power Rear Door'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Lexus+RX+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Lexus+RX+2'],
        },
        {
            make: 'Hyundai', model: 'Sonata', year: 2021, price: 24000, mileage: 22000, horsepower: 191, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Mid-size Sedan', engineVolume: 2.5, cylinders: 4, driveWheels: 'FWD', doors: 4, airbags: 9, wheel: 'Left', color: 'Shimmering Silver Pearl', interiorColor: 'Black', interiorMaterial: 'Cloth',
            exchange: false, technicalInspection: true, engineCode: 'Smartstream G2.5', paintCode: 'R2T', topSpeed: 135, zeroToSixty: 7.8, length: 192.9, width: 73.2, height: 56.9, wheelbase: 111.8, cargoCapacity: 16.0, groundClearance: 5.3,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['6-way Adjustable Driver Seat', 'Air Conditioning'],
            safety: ['Forward Collision-Avoidance Assist', 'Lane Following Assist', 'Driver Attention Warning'],
            multimedia: ['8-inch Touchscreen Display', 'Android Auto', 'Apple CarPlay'],
            other: ['16-inch Alloy Wheels', 'LED Headlights'],
            features: ['Forward Collision-Avoidance Assist', 'Driver Attention Warning', '8-inch Touchscreen Display'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Hyundai+Sonata+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Hyundai+Sonata+2'],
        },
        {
            make: 'Kia', model: 'Telluride', year: 2022, price: 43000, mileage: 11000, horsepower: 291, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Mid-size SUV', engineVolume: 3.8, cylinders: 6, driveWheels: 'AWD', doors: 4, airbags: 7, wheel: 'Left', color: 'Everlasting Silver', interiorColor: 'Black SynTex', interiorMaterial: 'Synthetic Leather',
            exchange: true, technicalInspection: true, engineCode: 'Lambda II', paintCode: 'KCS', topSpeed: 132, zeroToSixty: 7.1, length: 196.9, width: 78.3, height: 68.9, wheelbase: 114.2, cargoCapacity: 21.0, groundClearance: 8.0,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['One-Touch Sliding & Folding 2nd-Row Seats', 'Dual-Zone Automatic Climate Control'],
            safety: ['Safe Exit Assist', 'Rear Occupant Alert', 'Blind-Spot Collision-Avoidance Assist'],
            multimedia: ['10.25-inch Touchscreen', 'Navigation', 'Driver Talk'],
            other: ['18-inch Alloy Wheels', 'LED Headlights'],
            features: ['SynTex Seating Materials', 'UV-Talk and Driver Talk', 'Safe Exit Assist'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Kia+Telluride+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Kia+Telluride+2'],
        },
        {
            make: 'Nissan', model: 'Rogue', year: 2021, price: 28000, mileage: 19000, horsepower: 181, fuelType: 'Gasoline', transmission: 'CVT', bodyStyle: 'SUV',
            category: 'Compact Crossover SUV', engineVolume: 2.5, cylinders: 4, driveWheels: 'AWD', doors: 4, airbags: 10, wheel: 'Left', color: 'Super Black', interiorColor: 'Charcoal', interiorMaterial: 'Cloth',
            exchange: false, technicalInspection: true, engineCode: 'PR25DD', paintCode: 'KH3', topSpeed: 116, zeroToSixty: 8.2, length: 183.0, width: 72.4, height: 66.9, wheelbase: 106.5, cargoCapacity: 36.5, groundClearance: 8.2,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Remote Keyless Entry', 'Air Conditioning'],
            safety: ['Safety Shield 360', 'Intelligent Driver Alertness', 'Rear Door Alert'],
            multimedia: ['NissanConnect 8-inch Touchscreen', 'Apple CarPlay', 'Android Auto'],
            other: ['17-inch Aluminum-alloy Wheels', 'LED Headlights'],
            features: ['ProPILOT Assist', 'Safety Shield 360', 'Divide-N-Hide Cargo System'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Nissan+Rogue+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Nissan+Rogue+2'],
        },
        {
            make: 'Volkswagen', model: 'Golf', year: 2021, price: 23000, mileage: 16000, horsepower: 147, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Hatchback',
            category: 'Compact Car', engineVolume: 1.4, cylinders: 4, driveWheels: 'FWD', doors: 4, airbags: 6, wheel: 'Left', color: 'Pure White', interiorColor: 'Titan Black', interiorMaterial: 'Cloth',
            exchange: false, technicalInspection: true, engineCode: 'DGXA', paintCode: 'LC9A', topSpeed: 126, zeroToSixty: 7.6, length: 167.6, width: 70.8, height: 58.2, wheelbase: 103.6, cargoCapacity: 22.8, groundClearance: 5.4,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Heated Side Mirrors', 'Rain-sensing Windshield Wipers'],
            safety: ['Blind Spot Monitor', 'Front Assist', 'Rear Traffic Alert'],
            multimedia: ['App-Connect', '6.5-inch Touchscreen', 'Bluetooth'],
            other: ['16-inch Alloy Wheels', 'LED Taillights'],
            features: ['Blind Spot Monitor', 'Front Assist', 'App-Connect'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Volkswagen+Golf+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Volkswagen+Golf+2'],
        },
        {
            make: 'Mazda', model: 'CX-5', year: 2022, price: 29000, mileage: 13000, horsepower: 187, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Compact Crossover SUV', engineVolume: 2.5, cylinders: 4, driveWheels: 'AWD', doors: 4, airbags: 6, wheel: 'Left', color: 'Soul Red Crystal Metallic', interiorColor: 'Black', interiorMaterial: 'Leatherette',
            exchange: true, technicalInspection: true, engineCode: 'PY-VPS', paintCode: '46V', topSpeed: 127, zeroToSixty: 8.1, length: 179.1, width: 72.5, height: 65.3, wheelbase: 106.2, cargoCapacity: 30.8, groundClearance: 7.5,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Leather-wrapped Steering Wheel', 'Push Button Start', 'Heated Front Seats'],
            safety: ['i-ACTIVSENSE Safety Technology', 'Mazda Radar Cruise Control', 'Lane Departure Warning System'],
            multimedia: ['Mazda Connect Infotainment System', '10.25-inch Display', 'Apple CarPlay'],
            other: ['17-inch Alloy Wheels', 'LED Headlights with Auto-leveling'],
            features: ['i-ACTIVSENSE Safety Technology', 'Mazda Connect Infotainment System', 'G-Vectoring Control Plus'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Mazda+CX-5+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Mazda+CX-5+2'],
        },
        {
            make: 'Ram', model: '1500', year: 2021, price: 40000, mileage: 28000, horsepower: 305, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Truck',
            category: 'Full-size Truck', engineVolume: 3.6, cylinders: 6, driveWheels: '4WD', doors: 4, airbags: 6, wheel: 'Left', color: 'Diamond Black Crystal Pearl', interiorColor: 'Black', interiorMaterial: 'Cloth',
            exchange: true, technicalInspection: true, engineCode: 'Pentastar eTorque', paintCode: 'PXJ', topSpeed: 105, zeroToSixty: 7.5, length: 232.9, width: 82.1, height: 77.6, wheelbase: 144.5, cargoCapacity: 53.9, groundClearance: 8.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Air Conditioning', 'Cruise Control'],
            safety: ['ParkView Rear Back-Up Camera', 'Electronic Stability Control'],
            multimedia: ['Uconnect 3 with 5-inch Display', 'Bluetooth'],
            other: ['18-inch Steel Wheels'],
            features: ['Uconnect 12.0-inch Touchscreen', 'RamBox Cargo Management System', 'Active-Level Four Corner Air Suspension'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Ram+1500+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Ram+1500+2'],
        },
        {
            make: 'GMC', model: 'Sierra', year: 2021, price: 42000, mileage: 26000, horsepower: 355, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Truck',
            category: 'Full-size Truck', engineVolume: 5.3, cylinders: 8, driveWheels: '4WD', doors: 4, airbags: 6, wheel: 'Left', color: 'Summit White', interiorColor: 'Jet Black', interiorMaterial: 'Cloth',
            exchange: false, technicalInspection: true, engineCode: 'L84', paintCode: 'GAZ', topSpeed: 115, zeroToSixty: 6.2, length: 231.7, width: 81.2, height: 75.5, wheelbase: 147.4, cargoCapacity: 62.9, groundClearance: 7.9,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Single-zone Climate Control', 'Power Windows'],
            safety: ['StabiliTrak', 'Teen Driver Technology'],
            multimedia: ['GMC Infotainment System', '7-inch Touchscreen', 'Apple CarPlay'],
            other: ['17-inch Silver Painted Wheels'],
            features: ['MultiPro Tailgate', 'ProGrade Trailering System', 'GMC Infotainment System'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=GMC+Sierra+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=GMC+Sierra+2'],
        },
        {
            make: 'Acura', model: 'MDX', year: 2022, price: 50000, mileage: 14000, horsepower: 290, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Luxury Mid-size SUV', engineVolume: 3.5, cylinders: 6, driveWheels: 'AWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Lunar Silver Metallic', interiorColor: 'Ebony', interiorMaterial: 'Leatherette',
            exchange: true, technicalInspection: true, engineCode: 'J35Y6', paintCode: 'NH-830M', topSpeed: 112, zeroToSixty: 6.4, length: 198.4, width: 78.7, height: 67.1, wheelbase: 113.8, cargoCapacity: 18.1, groundClearance: 7.3,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Panoramic Moonroof', 'Tri-Zone Automatic Climate Control', 'Heated Front Seats'],
            safety: ['AcuraWatch', 'Collision Mitigation Braking System', 'Road Departure Mitigation'],
            multimedia: ['12.3-inch HD Dual-Content Center Display', 'Wireless Apple CarPlay', 'Wireless Android Auto'],
            other: ['19-inch Silver Wheels', 'Jewel Eye LED Headlights'],
            features: ['Super Handling All-Wheel Drive (SH-AWD)', 'AcuraWatch', 'Precision Cockpit'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Acura+MDX+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Acura+MDX+2'],
        },
        {
            make: 'Infiniti', model: 'QX60', year: 2022, price: 52000, mileage: 11000, horsepower: 295, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Luxury Mid-size SUV', engineVolume: 3.5, cylinders: 6, driveWheels: 'AWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Glacier White', interiorColor: 'Graphite', interiorMaterial: 'Leather-Appointed Seating',
            exchange: false, technicalInspection: true, engineCode: 'VQ35DD', paintCode: 'QAK', topSpeed: 120, zeroToSixty: 7.2, length: 198.2, width: 78.0, height: 69.7, wheelbase: 114.2, cargoCapacity: 14.5, groundClearance: 6.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Panoramic Moonroof', 'Tri-Zone Automatic Climate Control', 'Heated Front Seats'],
            safety: ['Forward Emergency Braking with Pedestrian Detection', 'Predictive Forward Collision Warning', 'Blind Spot Warning'],
            multimedia: ['InTouch 12.3-inch Interactive Display', 'Wireless Apple CarPlay', 'Android Auto'],
            other: ['20-inch Alloy Wheels', 'LED Headlamps'],
            features: ['ProPILOT Assist with Navi-link', 'Around View Monitor', 'Motion Activated Liftgate'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Infiniti+QX60+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Infiniti+QX60+2'],
        },
        {
            make: 'Volvo', model: 'XC90', year: 2021, price: 58000, mileage: 17000, horsepower: 316, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Luxury Mid-size SUV', engineVolume: 2.0, cylinders: 4, driveWheels: 'AWD', doors: 4, airbags: 7, wheel: 'Left', color: 'Crystal White Metallic', interiorColor: 'Charcoal', interiorMaterial: 'Leather',
            exchange: true, technicalInspection: true, engineCode: 'B4204T27', paintCode: '707', topSpeed: 112, zeroToSixty: 6.1, length: 195.0, width: 79.1, height: 69.9, wheelbase: 117.5, cargoCapacity: 15.8, groundClearance: 9.4,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Laminated Panoramic Moonroof', '4-Zone Electronic Climate System', 'Power-adjustable Front Seats'],
            safety: ['Pilot Assist', 'City Safety', 'Lane Keeping Aid'],
            multimedia: ['Sensus Connect', '9-inch Touchscreen', 'High Performance Audio System'],
            other: ['19-inch 6-Spoke Turbine Silver Alloy Wheels', 'Thor\'s Hammer LED Headlights'],
            features: ['Pilot Assist', 'City Safety', 'Sensus Connect'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Volvo+XC90+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Volvo+XC90+2'],
        },
        {
            make: 'Land Rover', model: 'Range Rover', year: 2021, price: 95000, mileage: 10000, horsepower: 355, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Luxury Full-size SUV', engineVolume: 3.0, cylinders: 6, driveWheels: '4WD', doors: 4, airbags: 6, wheel: 'Left', color: 'Fuji White', interiorColor: 'Ebony', interiorMaterial: 'Grained Leather',
            exchange: false, technicalInspection: true, engineCode: 'Ingenium', paintCode: '1AA', topSpeed: 130, zeroToSixty: 6.6, length: 196.9, width: 81.6, height: 73.6, wheelbase: 115.0, cargoCapacity: 31.8, groundClearance: 8.6,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Sliding Panoramic Roof', 'Three-zone Climate Control', 'Heated Front Seats'],
            safety: ['Terrain Response 2', 'Emergency Braking', 'Lane Keep Assist'],
            multimedia: ['Pivi Pro', '13.1-inch Touchscreen', 'Meridian Sound System'],
            other: ['21-inch Wheels', 'Premium LED Headlights'],
            features: ['Terrain Response 2', 'Pivi Pro', 'Meridian Sound System'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Land+Rover+Range+Rover+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Land+Rover+Range+Rover+2'],
        },
        {
            make: 'Jaguar', model: 'F-PACE', year: 2021, price: 60000, mileage: 15000, horsepower: 246, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'SUV',
            category: 'Luxury Compact SUV', engineVolume: 2.0, cylinders: 4, driveWheels: 'AWD', doors: 4, airbags: 6, wheel: 'Left', color: 'Santorini Black', interiorColor: 'Ebony', interiorMaterial: 'Luxtec',
            exchange: true, technicalInspection: true, engineCode: 'P250', paintCode: '1AG', topSpeed: 135, zeroToSixty: 6.9, length: 186.9, width: 81.5, height: 65.5, wheelbase: 113.1, cargoCapacity: 31.5, groundClearance: 8.4,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Sliding Panoramic Roof', 'Two-zone Climate Control', '10-way Electric Front Seats'],
            safety: ['Emergency Braking', 'Lane Keep Assist', 'Driver Condition Monitor'],
            multimedia: ['Pivi Infotainment System', '11.4-inch Touchscreen', 'Apple CarPlay'],
            other: ['19-inch 5 Spoke Wheels', 'Premium LED Headlights'],
            features: ['Pivi Infotainment System', 'Interactive Driver Display', 'Torque Vectoring by Braking'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Jaguar+F-PACE+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Jaguar+F-PACE+2'],
        },
        {
            make: 'Maserati', model: 'Ghibli', year: 2021, price: 75000, mileage: 12000, horsepower: 345, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Luxury Mid-size Sedan', engineVolume: 3.0, cylinders: 6, driveWheels: 'RWD', doors: 4, airbags: 7, wheel: 'Left', color: 'Nero Ribelle', interiorColor: 'Nero', interiorMaterial: 'Leather',
            exchange: false, technicalInspection: true, engineCode: 'F160', paintCode: 'NERO', topSpeed: 166, zeroToSixty: 5.5, length: 195.7, width: 76.6, height: 57.5, wheelbase: 118.0, cargoCapacity: 17.7, groundClearance: 4.5,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Sunroof', 'Dual-zone Automatic Climate Control', 'Heated Front Seats'],
            safety: ['Integrated Vehicle Control', 'Adaptive Cruise Control', 'Forward Collision Warning Plus'],
            multimedia: ['Maserati Touch Control Plus (MTC+)', '10.1-inch Touchscreen', 'Harman Kardon Premium Audio System'],
            other: ['19-inch Poseidone Wheels', 'Bi-Xenon Headlamps'],
            features: ['Maserati Touch Control Plus (MTC+)', 'Skyhook Performance Suspension', 'Harman Kardon Premium Audio System'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Maserati+Ghibli+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Maserati+Ghibli+2'],
        },
        {
            make: 'Ferrari', model: '488 GTB', year: 2019, price: 280000, mileage: 5000, horsepower: 661, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Coupe',
            category: 'Supercar', engineVolume: 3.9, cylinders: 8, driveWheels: 'RWD', doors: 2, airbags: 4, wheel: 'Left', color: 'Rosso Corsa', interiorColor: 'Nero', interiorMaterial: 'Leather',
            exchange: false, technicalInspection: true, engineCode: 'F154CB', paintCode: '322', topSpeed: 205, zeroToSixty: 3.0, length: 179.8, width: 76.9, height: 47.8, wheelbase: 104.3, cargoCapacity: 8.1, groundClearance: 4.0,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Dual-zone Climate Control'],
            safety: ['F1-Trac', 'Side Slip Control 2 (SSC2)', 'Carbon-ceramic Brakes'],
            multimedia: ['Infotainment System with Bluetooth'],
            other: ['20-inch Forged Wheels', 'Manettino Dial'],
            features: ['Side Slip Control 2 (SSC2)', 'F1-Trac', 'Manettino Dial'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Ferrari+488+GTB+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Ferrari+488+GTB+2'],
        },
        {
            make: 'Lamborghini', model: 'Huracan', year: 2020, price: 250000, mileage: 6000, horsepower: 631, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Coupe',
            category: 'Supercar', engineVolume: 5.2, cylinders: 10, driveWheels: 'AWD', doors: 2, airbags: 6, wheel: 'Left', color: 'Giallo Inti', interiorColor: 'Nero Ade', interiorMaterial: 'Alcantara',
            exchange: false, technicalInspection: true, engineCode: 'V10', paintCode: 'L0E2', topSpeed: 202, zeroToSixty: 2.9, length: 178.0, width: 76.1, height: 45.9, wheelbase: 103.1, cargoCapacity: 3.5, groundClearance: 4.5,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Automatic Climate Control'],
            safety: ['Carbon Ceramic Brakes', 'Electronic Stability Control'],
            multimedia: ['8.4-inch Touchscreen', 'Apple CarPlay'],
            other: ['20-inch Narvi Forged Wheels', 'ANIMA Selector'],
            features: ['Lamborghini Dinamica Veicolo Integrata (LDVI)', 'ANIMA', 'Carbon Ceramic Brakes'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Lamborghini+Huracan+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Lamborghini+Huracan+2'],
        },
        {
            make: 'McLaren', model: '720S', year: 2019, price: 300000, mileage: 4000, horsepower: 710, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Coupe',
            category: 'Supercar', engineVolume: 4.0, cylinders: 8, driveWheels: 'RWD', doors: 2, airbags: 4, wheel: 'Left', color: 'Onyx Black', interiorColor: 'Black Alcantara', interiorMaterial: 'Alcantara',
            exchange: false, technicalInspection: true, engineCode: 'M840T', paintCode: 'P14', topSpeed: 212, zeroToSixty: 2.8, length: 179.0, width: 76.0, height: 47.1, wheelbase: 105.1, cargoCapacity: 5.3, groundClearance: 3.9,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Dual-zone Climate Control'],
            safety: ['Proactive Chassis Control II', 'Variable Drift Control'],
            multimedia: ['8-inch Infotainment Screen', 'Bluetooth'],
            other: ['Folding Driver Display', 'Dihedral Doors'],
            features: ['Proactive Chassis Control II', 'Variable Drift Control', 'Folding Driver Display'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=McLaren+720S+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=McLaren+720S+2'],
        },
        {
            make: 'Bugatti', model: 'Chiron', year: 2018, price: 3000000, mileage: 2000, horsepower: 1479, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Coupe',
            category: 'Hypercar', engineVolume: 8.0, cylinders: 16, driveWheels: 'AWD', doors: 2, airbags: 4, wheel: 'Left', color: 'French Racing Blue', interiorColor: 'Terre d\'Or', interiorMaterial: 'Leather',
            exchange: false, technicalInspection: true, engineCode: 'W16', paintCode: 'BU001', topSpeed: 261, zeroToSixty: 2.4, length: 178.9, width: 80.2, height: 47.7, wheelbase: 106.7, cargoCapacity: 2.0, groundClearance: 3.7,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Climate Control', 'Bespoke Interior'],
            safety: ['Carbon Fiber Monocoque', 'High-performance Brakes'],
            multimedia: ['Accuton Sound System'],
            other: ['Top Speed Key', 'Sky View Roof'],
            features: ['Sky View', 'W16 Engine', 'Top Speed Key'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Bugatti+Chiron+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Bugatti+Chiron+2'],
        },
        {
            make: 'Rolls-Royce', model: 'Phantom', year: 2021, price: 450000, mileage: 7000, horsepower: 563, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Sedan',
            category: 'Ultra-luxury Sedan', engineVolume: 6.75, cylinders: 12, driveWheels: 'RWD', doors: 4, airbags: 8, wheel: 'Left', color: 'Diamond Black', interiorColor: 'Seashell', interiorMaterial: 'Leather',
            exchange: false, technicalInspection: true, engineCode: 'N74B68', paintCode: 'R32', topSpeed: 155, zeroToSixty: 5.1, length: 227.2, width: 79.4, height: 64.8, wheelbase: 139.8, cargoCapacity: 19.0, groundClearance: 5.5,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Starlight Headliner', 'Coach Doors', 'Refrigerated Console'],
            safety: ['Night Vision', 'Active Cruise Control', 'Surround View Camera'],
            multimedia: ['Bespoke Audio System', 'Rear Seat Entertainment'],
            other: ['The Gallery Dashboard', 'Self-righting Wheel Centers'],
            features: ['The Gallery', 'Starlight Headliner', 'Coach Doors'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Rolls-Royce+Phantom+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Rolls-Royce+Phantom+2'],
        },
        {
            make: 'Chevrolet', model: 'Silverado', year: 2021, price: 38000, mileage: 25000, horsepower: 355, fuelType: 'Gasoline', transmission: 'Automatic', bodyStyle: 'Truck',
            category: 'Full-size Truck', engineVolume: 5.3, cylinders: 8, driveWheels: '4WD', doors: 4, airbags: 6, wheel: 'Left', color: 'Shadow Gray Metallic', interiorColor: 'Jet Black', interiorMaterial: 'Cloth',
            exchange: true, technicalInspection: true, engineCode: 'L84', paintCode: 'GJI', topSpeed: 115, zeroToSixty: 6.1, length: 241.2, width: 81.2, height: 75.4, wheelbase: 157.0, cargoCapacity: 71.7, groundClearance: 7.9,
            vehicleHistoryUrl: 'https://www.carfax.com/',
            comfort: ['Climate Control', 'Cruise Control'],
            safety: ['StabiliTrak', 'Daytime Running Lamps'],
            multimedia: ['Chevrolet Infotainment 3', '7-inch Touchscreen', 'Bluetooth'],
            other: ['17-inch Bright Silver Painted Aluminum Wheels'],
            features: ['Trailering Package', 'Advanced Trailering System', 'Chevrolet Infotainment 3'],
            images: ['https://dummyimage.com/600x400/d1d5db/374151?text=Chevrolet+Silverado+1', 'https://dummyimage.com/600x400/d1d5db/374151?text=Chevrolet+Silverado+2'],
        },
    ];

    for (let i = 0; i < carsData.length; i++) {
        const car = carsData[i];
        const { images, ...carData } = car;
        const newCar = await prisma.car.create({
            data: {
                ...carData,
                vin: `VIN${i}${Math.random().toString(36).substring(2, 10)}`,
                stockNumber: `SN${i}${Math.random().toString(36).substring(2, 6)}`,
                owner: {
                    connect: {
                        id: user.id,
                    },
                },
            },
        });

        if (images && images.length > 0) {
            await prisma.carImage.createMany({
                data: images.map(url => ({
                    url,
                    carId: newCar.id,
                })),
            });
        }
    }

    const testimonials = [
        { name: 'Sarah Johnson', testimonial: 'The team at YourDealership made the entire car buying process a breeze. They were transparent, friendly, and incredibly knowledgeable. I found the perfect car for my family!', rating: 5 },
        { name: 'Michael Chen', testimonial: 'I was impressed with the curated selection of high-quality vehicles. No pressure, just great service. I\'ll definitely be back for my next purchase.', rating: 5 },
        { name: 'Emily Rodriguez', testimonial: 'As a first-time car buyer, I was nervous, but the staff guided me through every step. The financing options were flexible and easy to understand. Highly recommended!', rating: 5 },
    ];

    for (const t of testimonials) {
        await prisma.testimonial.create({
            data: t,
        });
    }

    console.log('Seeding finished.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });